### ISSUE TITLE
can't show image if the card name with "Æ" 

### ISSUE THREAD

**Issue by oskar1021** [thquinn/IsochronDrafter#1]
as title

**Comment by thquinn** [comment]
Are you sure? It works fine for me. In the newest version, a message box will pop up if it can't find an image: try this version and let me know what filename it's looking for.

**Comment by oskar1021** [comment]
like this
![image](https://cloud.githubusercontent.com/assets/11292333/6504553/95695ae8-c373-11e4-8b48-a973ae67a701.png)

**Comment by thquinn** [comment]
Weird. If Isochron Drafter is showing that message, though, that means it's getting a 404 from wherever the image is. It might be some irregularity in the way they're being hosted locally -- if you enter "http://localhost/Æther Breath.full.jpg" into your internet browser, does it come up? Failing that, please try hosting them online somewhere.
